import { Template } from '@/types'

export const TEMPLATES: Template[] = [
  {
    id: 'bp',
    icon: '📊',
    name: 'Business Plan',
    desc: 'Modèle complet en 5 sections',
    tags: ['Finances', 'Vision', 'Stratégie'],
    blocks: [
      { type: 'section', content: 'SECTION 01 // RÉSUMÉ EXÉCUTIF' },
      { type: 'text', content: 'Ce résumé présente les points saillants du plan stratégique. Notre vision est de devenir le leader de notre segment sur les marchés d\'Afrique de l\'Ouest d\'ici 2028, avec une croissance annuelle soutenue de 30%.' },
      { type: 'kpi' },
      { type: 'section', content: 'SECTION 02 // PRÉSENTATION DE L\'ENTREPRISE' },
      { type: 'text', content: 'Notre entreprise est spécialisée dans [secteur]. Notre mission est d\'offrir des solutions innovantes à nos clients tout en créant de la valeur durable pour nos parties prenantes. Nous opérons sur les marchés d\'Afrique de l\'Ouest avec une équipe de professionnels expérimentés.' },
      { type: 'section', content: 'SECTION 03 // ANALYSE DU MARCHÉ' },
      { type: 'text', content: 'Le marché adressable total (TAM) de notre secteur est estimé à 180 milliards FCFA en 2026, avec un taux de croissance annuel composé (CAGR) de 12,4%. Notre segment de marché disponible (SAM) représente environ 32 milliards FCFA. Les tendances macro-économiques régionales favorisent l\'émergence d\'acteurs locaux innovants.' },
      { type: 'section', content: 'SECTION 04 // STRATÉGIE COMMERCIALE' },
      { type: 'quote', content: '"L\'excellence opérationnelle et l\'innovation client sont les deux piliers de notre stratégie de croissance pour la période 2026-2030."' },
      { type: 'section', content: 'SECTION 05 // PROJECTIONS FINANCIÈRES (FCFA)' },
      { type: 'table' },
      { type: 'sign' },
    ],
  },
  {
    id: 'ao',
    icon: '📋',
    name: "Appel d'Offre",
    desc: 'Réponse structurée en 6 parties',
    tags: ['Proposition', 'Planning', 'Contrat'],
    blocks: [
      { type: 'section', content: "SECTION 01 // COMPRÉHENSION DU BESOIN" },
      { type: 'text', content: "En réponse au présent appel d'offre, notre équipe a conduit une analyse approfondie des spécifications techniques et fonctionnelles. Nous avons identifié trois enjeux majeurs : la performance opérationnelle, la conformité réglementaire et la maîtrise des coûts." },
      { type: 'section', content: 'SECTION 02 // RÉFÉRENCES & CAPACITÉS' },
      { type: 'text', content: "Depuis notre création, nous avons conduit plus de 40 missions similaires auprès d'acteurs publics et privés de la sous-région. Notre équipe projet est composée de consultants certifiés disposant d'une expertise sectorielle reconnue." },
      { type: 'kpi' },
      { type: 'section', content: 'SECTION 03 // PROPOSITION TECHNIQUE' },
      { type: 'text' },
      { type: 'section', content: 'SECTION 04 // MÉTHODOLOGIE & PLANNING' },
      { type: 'table' },
      { type: 'section', content: 'SECTION 05 // PROPOSITION COMMERCIALE (FCFA HT)' },
      { type: 'text', content: "Notre proposition tarifaire s'établit dans le respect des contraintes budgétaires indiquées, avec une décomposition transparente des postes de coûts. Les honoraires couvrent l'intégralité des livrables définis dans le cahier des charges." },
      { type: 'clause', content: "Article 1. — Conditions de Paiement\nLes paiements s'effectueront selon l'échéancier suivant : 40% à la signature de l'ordre de service, 40% à la livraison du rapport intermédiaire, et le solde de 20% à l'acceptation du livrable final. Tout retard de paiement supérieur à 15 jours calendaires entraînera l'application de pénalités de retard au taux légal en vigueur." },
      { type: 'sign' },
    ],
  },
  {
    id: 'audit',
    icon: '🔍',
    name: "Rapport d'Audit",
    desc: 'Constatations, risques & recommandations',
    tags: ['Risques', 'Constatations', 'KPIs'],
    blocks: [
      { type: 'section', content: 'SECTION 01 // SYNTHÈSE EXÉCUTIVE' },
      { type: 'quote', content: '"Le présent rapport constitue une évaluation exhaustive et indépendante des processus organisationnels et financiers sur la période de référence."' },
      { type: 'kpi' },
      { type: 'section', content: 'SECTION 02 // PÉRIMÈTRE & MÉTHODOLOGIE' },
      { type: 'text', content: "L'audit a été conduit conformément aux normes ISA et aux référentiels COSO sur la période du 1er janvier au 31 décembre 2025. Le périmètre couvre les fonctions Finances, RH, Achats et Systèmes d'Information. Nos travaux ont inclus des entretiens avec 18 collaborateurs, l'analyse de 340 documents et des tests sur 85 transactions." },
      { type: 'section', content: 'SECTION 03 // CONSTATATIONS PRINCIPALES' },
      { type: 'text' },
      { type: 'table' },
      { type: 'section', content: 'SECTION 04 // ANALYSE DES RISQUES' },
      { type: 'text', content: "Notre analyse identifie 4 zones à surveiller : la concentration des pouvoirs de signature, le délai de recouvrement des créances (DRC moyen 78 jours vs standard 45), l'absence de politique formalisée de gestion des accès informatiques, et la dépendance à un fournisseur unique pour 43% des achats." },
      { type: 'section', content: 'SECTION 05 // RECOMMANDATIONS STRATÉGIQUES' },
      { type: 'text' },
      { type: 'sign' },
    ],
  },
  {
    id: 'memo',
    icon: '📝',
    name: 'Note de Direction',
    desc: 'Communication interne formelle',
    tags: ['Mémo', 'Décision', 'Interne'],
    blocks: [
      { type: 'section', content: 'OBJET // NOTE DE SERVICE' },
      { type: 'text', content: `La présente note a pour objet de porter à la connaissance de l'ensemble du personnel de Direction les décisions prises en Comité Exécutif du ${new Date().toLocaleDateString('fr-FR')}. Ces dispositions entrent en vigueur à compter de la date de diffusion du présent document.` },
      { type: 'quote', content: '"La cohérence de nos décisions opérationnelles est le socle de notre performance collective."' },
      { type: 'section', content: 'DÉCISIONS & DISPOSITIONS' },
      { type: 'text' },
      { type: 'divider' },
      { type: 'section', content: 'MISE EN ŒUVRE & CALENDRIER' },
      { type: 'table' },
      { type: 'sign' },
    ],
  },
  {
    id: 'contrat',
    icon: '⚖️',
    name: 'Contrat / Convention',
    desc: 'Cadre contractuel avec clauses',
    tags: ['Clauses', 'OHADA', 'Signature'],
    blocks: [
      { type: 'section', content: 'ENTRE LES SOUSSIGNÉS' },
      { type: 'text', content: "D'une part, [Entité], société [forme juridique] au capital de [capital] FCFA, immatriculée au RCCM sous le numéro [RCCM], dont le siège social est sis à [adresse], représentée par [signataire], agissant en qualité de Directeur Général, ci-après désignée « le Prestataire ».\n\nD'autre part, [Nom Client], ci-après désignée « le Client »." },
      { type: 'section', content: 'ARTICLE 1 — OBJET DU CONTRAT' },
      { type: 'clause', content: "Article 1. — Objet\nLe présent contrat a pour objet de définir les conditions et modalités dans lesquelles le Prestataire s'engage à fournir au Client les prestations de services définies à l'Annexe I, et ce pour la durée stipulée à l'article 3." },
      { type: 'section', content: 'ARTICLE 2 — CONDITIONS FINANCIÈRES (FCFA)' },
      { type: 'clause', content: "Article 2. — Rémunération\nEn contrepartie des prestations réalisées, le Client versera au Prestataire la somme forfaitaire définie dans le devis annexé, payable selon les modalités suivantes : 40% à la signature, 40% à mi-parcours, 20% à la livraison finale." },
      { type: 'clause', content: "Article 3. — Durée & Résiliation\nLe présent contrat prend effet à compter de sa signature par les deux parties pour une durée déterminée de [durée]. Il peut être résilié par l'une ou l'autre des parties moyennant un préavis de 30 jours, adressé par lettre recommandée avec accusé de réception." },
      { type: 'clause', content: "Article 4. — Confidentialité\nLes parties s'engagent à maintenir strictement confidentielle toute information, donnée ou document appartenant à l'autre partie dont elles pourraient avoir connaissance dans le cadre du présent contrat, et ce pendant une durée de 5 ans après son expiration." },
      { type: 'clause', content: "Article 5. — Droit Applicable & Juridiction\nLe présent contrat est régi par le droit OHADA et la législation nationale applicable. En cas de différend, les parties s'engagent à rechercher une solution amiable. À défaut, le litige sera soumis au Tribunal de Commerce compétent." },
      { type: 'divider' },
      { type: 'sign' },
    ],
  },
]

export const PALETTE = [
  '#1B4FD8', '#0F172A', '#1A3C5E', '#14532D',
  '#4A1D96', '#7C2D12', '#1E3A5F', '#374151',
  '#065F46', '#7F1D1D',
]
